# Generated by Django 5.2.4 on 2025-07-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='estimated_employees',
            new_name='employee_need',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='telephone',
            new_name='telephone_number',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='contact_swish',
            new_name='through_swish_or_telephone',
        ),
        migrations.AddField(
            model_name='job',
            name='site_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/job_photos'),
        ),
        migrations.AlterField(
            model_name='job',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
