# Generated by Django 5.2.4 on 2025-07-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('cancelled', 'cancelled')], default='open', max_length=10),
        ),
    ]
