# Generated by Django 5.2.4 on 2025-08-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_areas', to='jobs.area'),
        ),
    ]
