# Generated by Django 5.2.4 on 2025-07-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_estimated_employees_job_employee_need_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='site_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/site_photos'),
        ),
    ]
