# Generated by Django 5.2.4 on 2025-07-23 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.category'),
            preserve_default=False,
        ),
    ]
