# Generated by Django 5.2.4 on 2025-07-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
