# Generated by Django 5.2.4 on 2025-07-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_sub_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/category_icons'),
        ),
    ]
