# Generated by Django 5.2.4 on 2025-07-29 04:59

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_review_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPauseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reasons', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Job is postponed'), (2, 'Found a business outside swish.ma'), (3, 'Job is cancelled'), (4, 'Mistaken post'), (5, 'Budget or requirements changed'), (5, 'Other')], max_length=11)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'Pause Reasons',
                'ordering': ['job'],
            },
        ),
    ]
