# Generated by Django 5.2.4 on 2025-07-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobpausereason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpausereason',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
