# Generated by Django 5.2.4 on 2025-07-29 05:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobpausereason_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpausereason',
            name='Reasons',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Job is postponed'), (2, 'Found a business outside swish.ma'), (3, 'Job is cancelled'), (4, 'Mistaken post'), (5, 'Budget or requirements changed'), (6, 'Other')], max_length=11),
        ),
    ]
