# Generated by Django 5.2.4 on 2025-07-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobpausereason_reasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpausereason',
            old_name='Reasons',
            new_name='reasons',
        ),
    ]
