# Generated by Django 5.2.4 on 2025-07-29 05:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_rename_reasons_jobpausereason_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpausereason',
            name='reasons',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Job is postponed', 'Job is postponed'), ('Found a business outside swish.ma', 'Found a business outside swish.ma'), ('Job is cancelled', 'Job is cancelled'), ('Mistaken post', 'Mistaken post'), ('Budget or requirements changed', 'Budget or requirements changed'), ('Other', 'Other')], max_length=118),
        ),
    ]
