# Generated by Django 5.2.4 on 2025-07-31 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_area_job_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_areas', to='jobs.area'),
        ),
    ]
