# Generated by Django 5.2.4 on 2025-07-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name_plural': 'Areas'},
        ),
    ]
