# Generated by Django 5.2.4 on 2025-08-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_customcategory_alter_job_category_job_odd_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='odd_category',
            new_name='custom_category',
        ),
    ]
