# Generated by Django 5.2.4 on 2025-08-03 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_rename_odd_category_job_custom_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='site_photo',
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/site_images')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'site images',
            },
        ),
    ]
