# Generated by Django 5.2.4 on 2025-08-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_remove_job_site_photo_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scale',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large')], max_length=10, null=True),
        ),
    ]
