# Generated by Django 5.2.4 on 2025-08-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_job_scale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='scale',
            new_name='size',
        ),
    ]
