# Generated by Django 5.2.4 on 2025-07-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Complete', 'Complete'), ('Rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
