# Generated by Django 5.2.4 on 2025-08-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['role'], 'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='role',
        ),
    ]
