# Generated by Django 5.2.4 on 2025-08-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
