# Generated by Django 5.2.4 on 2025-07-29 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobpausereason_reasons'),
        ('service_provider', '0002_alter_bid_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='clip_balance',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='clip_granted_at',
        ),
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=True)),
                ('package_name', models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Pro', 'Pro'), ('Elite', 'Elite')])),
                ('package_balance', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='jobs.job')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.tokenpackage')),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'used_by')},
            },
        ),
        migrations.DeleteModel(
            name='ClipTransaction',
        ),
    ]
