# Generated by Django 5.2.4 on 2025-08-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0004_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='friday_time',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='monday_time',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='saturday_time',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='sunday_time',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='thursday_time',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='tuesday_time',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='wednesday_time',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
