# Generated by Django 5.2.4 on 2025-08-15 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_code'),
        ('service_provider', '0005_remove_companyprofile_friday_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpackage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_transaction', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='service_provider.tokenpackage'),
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='used_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
