# Generated by Django 5.2.4 on 2025-07-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_companyprofile_about_companyprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
