# Generated by Django 5.2.4 on 2025-07-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_companyprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='open_in_weekend',
            field=models.BooleanField(default=False),
        ),
    ]
