# Generated by Django 5.2.4 on 2025-08-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_alter_tokenpackage_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpackage',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
