# Generated by Django 5.2.4 on 2025-07-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0007_companyprofile_open_in_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='business_email',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
