# Generated by Django 5.2.4 on 2025-07-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_area_job_area'),
        ('service_provider', '0008_companyprofile_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='area',
            field=models.ManyToManyField(blank=True, to='jobs.area'),
        ),
    ]
