# Generated by Django 5.2.4 on 2025-08-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0009_companyprofile_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Complete', 'Complete'), ('Rejected', 'Rejected')], default='Active', max_length=10, null=True),
        ),
    ]
