# Generated by Django 5.2.4 on 2025-07-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_number',
            new_name='ice_number',
        ),
    ]
