# Generated by Django 5.2.4 on 2025-07-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_company_number_user_ice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('role', models.CharField(choices=[('private', 'Private'), ('company', 'Company')], max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ice_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'PreSubscription',
                'verbose_name_plural': 'PreSubscription Before Launching',
            },
        ),
    ]
