# Generated by Django 5.2.4 on 2025-07-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image_user_language_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=2, max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
