# Generated by Django 5.2.4 on 2025-07-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_presubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presubscription',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
