# Generated by Django 5.2.4 on 2025-07-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ice_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_categories',
        ),
    ]
